trigger:
  batch: "true"
  branches:
    include:
      - master

pr:
  autoCancel: "true"
  branches:
    include:
      - master
      
jobs:

- job: ProdDeploy
  displayName: Production Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - powershell:

      $files = $(git diff HEAD HEAD~ --name-only);
      $temp = $files -split ' ';
      $count = $temp.Length;
      Write-Output "Total changed $count files";
      For ($i=0; $i -lt $temp.Length; $i++){
        $nameOfChangedFile = $temp[$i];
        echo "Changed File - $nameOfChangedFile";
      }
      $EmFrom = "Enter From Email";
      $username = "Enter User Name";
      $pwd = "Enter Password";
      $EmTo = " Enter To Email ";
      $Server = " Enter SMTP Server Name ";
      $port = 000;
      $Subj = "Following are the components modified";
      $Bod = $temp;
      $securepwd = ConvertTo-SecureString $pwd -AsPlainText -Force;
      $cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $securepwd;
      Send-MailMessage -To $EmTo -From $EmFrom -Body $Bod -Subject $Subj -SmtpServer $Server -port $port -Credential $cred;
