# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $(PAT_TOKEN)
  - powershell: |

       echo $(PAT_TOKEN)
       echo $env:AZURE_DEVOPS_EXT_PAT
       echo $(allowAutoMerge);
       if($(allowAutoMerge) -eq 1){
          Write-Host "##vso[task.setvariable variable=isCommitFromHotFix;]1";
          write-host("*****Initiating AutoMerge To master******");
          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          # Write-Host "##vso[task.setvariable variable=isCommitFromHotFix;]testValue";

          az devops login --organization https://dev.azure.com/PrashantsaxenaSF/
          # Base64-encodes the Personal Access Token (PAT) appropriately
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "","$(PAT_TOKEN)")))
          $url = "https://dev.azure.com/PrashantsaxenaSF/TestProject-Vivek/_apis/distributedtask/variablegroups/1?api-version=5.0-preview.1"

          $json = '{"id":2,"type":"Vsts","name":"TestVariableGroup","variables":{"isCommitFromHotFix":{"isSecret":false,"value":"0931"}}}'
          $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}
          Write-Host "New Variable Value:" $pipeline.variables.isCommitFromHotFix.value 
       }else {
          write-host("No Auto Merge")
       }
       
      