trigger:
  batch: "true"
  branches:
    include:
      - master

pr:
  autoCancel: "true"
  branches:
    include:
      - master
      
jobs:

- job: ProdDeploy
  displayName: Production Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - powershell:

      $files = $(git diff HEAD HEAD~ --name-only);
      $temp = $files -split ' ';
      $count = $temp.Length;
      Write-Output "Total changed $count files";
      For ($i=0; $i -lt $temp.Length; $i++){
        $nameOfChangedFile = $temp[$i];
        echo "Changed File - $nameOfChangedFile";
      }

      $emailSmtpServer = "mail"
      $emailSmtpServerPort = "587"
      $emailSmtpUser = "user"
      $emailSmtpPass = "P@ssw0rd"
      
      $emailFrom = "vj.vivekjoshi@gmail.com"
      $emailTo = "vj.vivekjoshi@gmail.com"
      $emailcc="vj.vivekjoshi@gmail.com"
      
      $emailMessage = New-Object System.Net.Mail.MailMessage( $emailFrom , $emailTo )
      $emailMessage.cc.add($emailcc)
      $emailMessage.Subject = "subject" 
      $emailMessage.Body = "body"
      
      $SMTPClient = New-Object System.Net.Mail.SmtpClient( $emailSmtpServer , $emailSmtpServerPort )
      $SMTPClient.EnableSsl = $False
      $SMTPClient.Credentials = New-Object System.Net.NetworkCredential( $emailSmtpUser , $emailSmtpPass );
      $SMTPClient.Send( $emailMessage )