# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
      
jobs:

- job: AutoMergeToMaster
  variables:
  - group: TestVariableGroup
  displayName: Auto Merge
  steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - powershell: |
       Write-Output $TestVariableGroup.allowAutoMerge
       Write-Output $allowAutoMerge
       git --version
       git config --global user.email "Prashantsxn8@gmail.com"
       git config --global user.name "Prashantsaxena88811"
       git checkout feature/Test1234
       git pull origin feature/Test1234
       git checkout master
       git merge feature/Test1234
       git push origin master
      