# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#get the changed template
$a = git diff-tree 
echo "file names :$a"
#--no-commit-id --name-only -r $(Build.SourceVersion)
#assign the filename to a variable
#echo "##vso[task.setvariable variable=fileName]$a" 

#- script: |
#   echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
