# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $PAT_TOKEN
      SYSTEM_ACCESSTOKEN: $System.AccessToken
  - powershell: |

       Write-Host $(PAT_TOKEN)
       Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
       Write-Host $env:AZURE_DEVOPS_EXT_PAT
       Write-Host $(allowAutoMerge);
       Write-Host $System.AccessToken

       if($(allowAutoMerge) -eq 1){

          Write-Host "Before " $(isCommitFromHotFix)
          Write-Host "##vso[task.setvariable variable=isCommitFromHotFix;]crushed tomatoes"
          Write-Host "After " $(isCommitFromHotFix)
          
          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          
          $user = "Prashant.saxenaSF@outlook.com"
          $token = "PrashantSF@123"
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user,$token)))

              
          $Url = "https://dev.azure.com/PrashantsaxenaSF/TestProject-Vivek/_apis/distributedtask/variablegroups/2?api-version=5.1-preview.1"
          function createJsonBody{
            # $value = '{"id":2,"type":"Vsts","name":"TestVariableGroup","variables":{"isCommitFromHotFix":{"value":"0931"}}}'
            $value = '{"variables":{"allowAutoMerge":{"value":"value1"}},"id":2,"type":"Vsts","name":"TestVariableGroup"}'
            return $value
           }
          # $jsonBody='{"variables": {"allowAutoMerge": {"value": "value1"},"isCommitFromHotFix": {"value": "value2"}},"type": "Vsts","name": "TestVariableGroup","description": "Updated variable group"}
          $jsonBody = createJsonBody
          write-host " jsonBody is " $jsonBody

          $user = "Prashant.saxenaSF@outlook.com"
          $pass= "PrashantSF@123"
          $pair = "${user}:${pass}"
          $bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)
          $base64 = [System.Convert]::ToBase64String($bytes)
          $basicAuthValue = "Basic $base64"
          $headers = @{ Authorization = $basicAuthValue }

          $outResult = Invoke-RestMethod -Uri $Url -Method Put -Body $jsonBody -ContentType "application/json" -Headers $headers
          # $outResult = Invoke-RestMethod -Uri $Url -Method Put -Body $jsonBody -ContentType "application/json" -Headers @{Authorization = "Bearer $PAT_TOKEN"}
          # 
          Write-Host $(allowAutoMerge);
         }else {
          write-host("No Auto Merge")
       }
       

 