# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $(PAT_TOKEN)
  - powershell: |

       echo $(PAT_TOKEN)
       echo $env:AZURE_DEVOPS_EXT_PAT
       echo $(allowAutoMerge);
       if($(allowAutoMerge) -eq 1){
          Write-Host "##vso[task.setvariable variable=isCommitFromHotFix;]1";
          write-host("*****Initiating AutoMerge To master******");
          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          Write-Host "##vso[task.setvariable variable=isCommitFromHotFix;]testValue";

          $id = 2

          # This is using some environment variables provided by the pipeline to build the URL
          $url = ("$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/distributedtask/variablegroups/{0}?api-version=5.0-preview" -f $id)

          # You might find it useful to us a GET method to grab the variable group, update it and then convert it to this json string rather than doing this here
          $json = '{"id":$id,"type":"Vsts","name":"TestVariableGroup","<Variable Name":{"isCommitFromHotFix":{"isSecret":false,"value":"1"}}}'

          $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"}

       }else {
          write-host("No Auto Merge")
       }
       
      