# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $(PAT_TOKEN)
  - powershell: |

       echo $(PAT_TOKEN)
       $env:AZURE_DEVOPS_EXT_PAT = $(PAT_TOKEN)
       echo $(allowAutoMerge);
       if($(allowAutoMerge) -eq 1){
          write-host("*****Initiating AutoMerge To master******");
          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          
          az devops login --organization https://dev.azure.com/PrashantsaxenaSF/
          az pipelines variable-group variable update --group-id 2 --name isCommitFromHotFix --value 1 --organization https://dev.azure.com/PrashantsaxenaSF/ --project TestProject-Vivek
       }else {
          write-host("No Auto Merge")
       }
       
      