# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
      
jobs:

- job: ProdDeploy
  displayName: Production Deploy
  steps:
  - powershell:

        git checkout feature/Test1234
        git pull origin feature/Test1234
        git checkout master
        git merge feature/Test1234
        git push origin master