trigger:
  batch: "true"
  branches:
    include:
      - master

pr:
  autoCancel: "true"
  branches:
    include:
      - master
      
jobs:

- job: ProdDeploy
  displayName: Production Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - powershell:

      $files = $(git diff HEAD HEAD~ --name-only);
      $temp = $files -split ' ';
      $count = $temp.Length;
      Write-Output "Total changed $count files";
      For ($i=0; $i -lt $temp.Length; $i++){
        $nameOfChangedFile = $temp[$i];
        echo "Changed File - $nameOfChangedFile";
      }

      $From = "vivek@infoglen.com";
      $To = "vivek@infoglen.com";
      $Cc = "vivek@infoglen.com";
      $Subject = "Commit Changes";
      $Body = "<h2>Hi, look at these pics of Drogon!</h2><br><br>";
      $Body += "He is so cute!";
      $SMTPServer = "smtp.mailtrap.io";
      $SMTPPort = "587";
      $secpasswd = ConvertTo-SecureString "536bff7d790825" -AsPlainText -Force
      $cred = New-Object System.Management.Automation.PSCredential ("f12fc43b8d0185", $secpasswd)
      Send-MailMessage -SmtpServer SMTPServer -Credential $cred -UseSsl -From $From -to $To -Cc $Cc -Subject $Subject -Body $Body -BodyAsHtml