# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $(PAT_TOKEN)
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    

  - powershell: |

       echo $(PAT_TOKEN)
       Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
       echo $env:AZURE_DEVOPS_EXT_PAT
       echo $(allowAutoMerge);
       if($(allowAutoMerge) -eq 1){

           Write-Host "##vso[task.setvariable variable="isCommitFromHotFix";value=23]23";
           Write-Host "##vso[task.setVariable variable=TestVariableGroup;]{'isCommitFromHotFix':{'value':'A'}}"
          # write-host("*****Initiating AutoMerge To master******");
          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master

          # echo $env:AZURE_DEVOPS_EXT_PAT | az devops login
          # az devops configure -d organization = https://dev.azure.com/PrashantsaxenaSF/TestProject-Vivek
          # az pipelines variable-group variable update --id 2 --name isCommitFromHotFix --value 2

          # Base64-encodes the Personal Access Token (PAT) appropriately
          # $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "","$(PAT_TOKEN)")))
          # $url = "https://dev.azure.com/PrashantsaxenaSF/TestProject-Vivek/_apis/distributedtask/variablegroups/2?api-version=5.0-preview.1"

          # $json = '{"id":2,"type":"Vsts","name":"TestVariableGroup","variables":{"isCommitFromHotFix":{"isSecret":false,"value":"0931"}}}'
           # $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}
          # $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{
          #    Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          # }
          # Write-Host "New Variable Value:" $pipeline.variables.isCommitFromHotFix.value 
      
          # $url = "https://dev.azure.com/PrashantsaxenaSF/TestProject-Vivek/_apis/distributedtask/variablegroups/2?api-version=5.0-preview.1"
          # Write-Host $url

          # function CreateJsonBody{
           # $value = '{"id":2,"type":"Vsts","name":"TestVariableGroup","variables":{"isCommitFromHotFix":{"value":"0931"}}}'
           # return $value
          # }
          # $json = CreateJsonBody
          # $pipeline = Invoke-RestMethod -Uri $url -Method Put -Body $json -ContentType "application/json" -Headers @{
             # Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          # }

          # Write-Host "New Variable Value:" $pipeline.variables.isCommitFromHotFix.value


          $collectionurl = "https://dev.azure.com/PrashantsaxenaSF"; 
          $project = "TestProject-Vivek";
          $variablegroupid = "2";
          $variableName = "isCommitFromHotFix";
          $user = "Prashant.saxenaSF@outlook.com";
          $token = $PAT_TOKEN;
          # Base64-encodes the Personal Access Token (PAT) appropriately
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user,$token)))
          $baseUri = "$collectionurl/$project/_apis/distributedtask/variablegroups/$($variablegroupid)?api-version=5.0-preview.1"
          $vgresponse = Invoke-RestMethod -Method Get -Uri $baseUri -Headers @{
              Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
           }
          # Set new value for the specific variable
          echo $(vgresponse.variables)
          function CreateJsonBody{
            $value = '{"id":2,"type":"Vsts","name":"TestVariableGroup","variables":{"isCommitFromHotFix":{"value":"0931"}}}'
            return $value
          }
          # $vgresponse.variables.$variableName.Value = "0711"
          ####****************** update the modified object **************************
          $json = CreateJsonBody 
          # @($vgresponse) | ConvertTo-Json -Depth 99
          $updatedvg = Invoke-RestMethod -Uri $baseUri -Method Put -Body $json -ContentType "application/json" -Headers @{
              Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          }
          Cls
          write-host "==========================================================" 
          Write-host "The value of Varialbe '$variableName' is updated to" $updatedvg.variables.$variableName.value
          write-host "=========================================================="

         }else {
          write-host("No Auto Merge")
       }
       
      