# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $PAT_TOKEN
      SYSTEM_ACCESSTOKEN: $System.AccessToken
  - powershell: |

       Write-Host $(PAT_TOKEN)
       Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"
       Write-Host $env:AZURE_DEVOPS_EXT_PAT
       Write-Host $(allowAutoMerge);
       Write-Host $System.AccessToken

       if($(allowAutoMerge) -eq 1){

          Write-Host "Before " $(isCommitFromHotFix)
          Write-Host "##vso[task.setvariable variable=isCommitFromHotFix;]crushed tomatoes"
          Write-Host "After " $(isCommitFromHotFix)
          
          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          
    
         }else {
          write-host("No Auto Merge")
       }
       

 