# Starter pipeline : AutoMerge Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: "true"
  branches:
    include:
      - feature/Test1234

pr:
  autoCancel: "true"
  branches:
    include:
      - feature/Test1234
variables:
  - group: TestVariableGroup
      
jobs:

- job: AutoMergeToMaster
  displayName: Auto Merge
  steps: 
  - checkout: self
    persistCredentials: true
    clean: true
    env:
      AZURE_DEVOPS_EXT_PAT: $PAT_TOKEN
      SYSTEM_ACCESSTOKEN: $System.AccessToken
  - powershell: |

       if($(allowAutoMerge) -eq 1){

          git --version
          git config --global user.email "Prashantsxn8@gmail.com"
          git config --global user.name "Prashantsaxena88811"
          git checkout feature/Test1234
          git pull origin feature/Test1234
          git checkout master
          git merge feature/Test1234
          git push origin master
          
          $user = "Prashant.saxenaSF@outlook.com"
          #$token = "w6hmwl5giih6wchrrxckertlsepwlloqhs3me2ejv424z3curtpa"
          #$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user,$token)))

          $personalAccessToken = $PAT_TOKEN
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user,$personalAccessToken)))
          $accountname = "dev.azure.com"
          $variableGroupName = "myvariablegroup"
          $projectName = "TestProject-Vivek"

          $vstsUri = "https://" + $accountname + "/"
          #+ ".visualstudio.com/"

          # GET https://{accountName}.visualstudio.com/{project}/_apis/distributedtask/variablegroups?api-version=4.1-preview.1
          # get variable groups and find our one
          $call = $vstsUri + $projectName + "/_apis/distributedtask/variablegroups?api-version=4.1-preview.1"
          $result = Invoke-RestMethod -Uri $call -Method Get -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}

          $groupId = (-1)
          foreach($group in $result.value) {
              if($group.name.Equals($variableGroupName)) {

                  $groupId = $group.id
                  break;
              }
          }
          Write-Host $groupId 
          # if we can't find the group, throw an error
          if($groupId -lt 0) {

              throw("Couldn't find group")

          }

          # get full json for our group
          $call = $vstsUri + $projectName + "/_apis/distributedtask/variablegroups/" + $groupId + "?api-version=4.1-preview.1"
          $group = Invoke-RestMethod -Uri $call -Method Get -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}

          # https://docs.microsoft.com/en-us/rest/api/vsts/_apis/distributedtask/variablegroups/variablegroups/update?view=vsts-rest-4.1
          # update variable group by id
          $group.variables.sendNotification = @{}
          $group.variables.sendNotification += @{"value" = "New Secret Value"}
          $group.variables.sendNotification += @{"isSecret" = $true}

          $call = $vstsUri + $projectName + "/_apis/distributedtask/variablegroups/" + $groupId + "?api-version=4.1-preview.1"
          $result = Invoke-RestMethod -Uri $call -Method Put -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Body (ConvertTo-Json $group -Depth 10)      

         }else {
          write-host("No Auto Merge")
       }
       

 